name: Create release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python 3.11.3
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.3"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Build executable
      run: pyinstaller --noconfirm --onefile --console --name "HD2SD" "src/main.py"
    
#     - name: Upload artifact
#       uses: actions/upload-artifact@v3
#       with:
#         name: HD2SD
#         path: ./HD2SD.exe

    - name: Generate release tag
      id: tag
      run: echo "::set-output name=release_tag::Nightly_$(date +"%Y.%m.%d_%H-%M")"

    - name: Upload to release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: HD2SD.exe
